application: s~sauer-pda
version: YYYY-MM-DD-rXXX
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
 
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py
  login: admin
  secure: always
