application: s~sauer-pda
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
 
- url: /.*
  script: main.py
  login: admin
  secure: always
