application: s~sauer-pda
version: 
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
 
- url: /.*
  script: main.py
  login: admin
  secure: always
